### ISSUE TITLE
[1.25]Update CNI plugins to v1.1.1

### ISSUE THREAD

**Issue by pacoxu** [klts-io/kubernetes-lts#201]
https://github.com/klts-io/kubernetes-lts/blob/8fb749e869b85d58ef95c993f5a9dc568accc5cc/rpm/kubelet/kubelet.spec#L13

https://github.com/tpepper/release/commit/e35146e831035f92c2b1146f6c7431bc6e580e24#diff-57f10b7808ebe7110b2c66a39232cdaa30806a44f1c8f26d8adc297a1bd019faR160

1.25.0
- Update CNI plugins to v1.1.1

**Comment by pacoxu** [comment]
```
kubelet:
  - versionConstraint: ">= 1.24.0 < 1.24.5"
    sourceURLTemplate: "{{ KubernetesURL }}"
    dependencies:
      - name: kubernetes-cni
        versionConstraint: ">= 0.8.7"
  - versionConstraint: ">= 1.24.5 < 1.25.0"
    sourceURLTemplate: "{{ KubernetesURL }}"
    dependencies:
      - name: kubernetes-cni
        versionConstraint: ">= 1.1.1"
  - versionConstraint: "1.25.0"
    sourceURLTemplate: "{{ KubernetesURL }}"
    dependencies:
      - name: kubernetes-cni
        versionConstraint: ">= 0.8.7"
  - versionConstraint: ">= 1.25.1 < 1.28.0"
    sourceURLTemplate: "{{ KubernetesURL }}"
    dependencies:
      - name: kubernetes-cni
        versionConstraint: ">= 1.1.1"
  - versionConstraint: ">= 1.28.0"
    sourceURLTemplate: "{{ KubernetesURL }}"
    dependencies:
      - name: kubernetes-cni
        versionConstraint: ">= 1.2.0"
```

From https://github.com/kubernetes/release/blob/master/cmd/krel/templates/latest/metadata.yaml
